### ISSUE TITLE
Tip [DO5]: Controllers, services, repositories

### ISSUE THREAD

**Issue by arothuis-hu** [aminzammou/cisq1-lingo#2]
# Controllers
Denk aan resource-based REST URLs:
* nieuwe ronde --> `POST /game/{id}/round`
* nieuwe raadpoging --> `POST /game/{id}/guess` of `PATCH /game/{id}/guess`

Misschien wil je ook een GET maken voor het opvragen van de Progress van één trainingsessie?

https://github.com/aminzammou/cisq1-lingo/blob/9874b08d394af5e8312271024c08ac756fddf141/src/main/java/nl/hu/cisq1/lingo/trainer/presentation/TrainerController.java#L8-L25

# Services
Je zou in elke service een Progress kunnen teruggeven. Dan geef je altijd dezelfde "view" terug van de huidige spel toestand. Let op dat de ID pas toegevoegd wordt aan het spel nadat deze gesavet is.

Misschien moet je een losse `Progress getCurrentProgress()` aanmaken op de Game.

https://github.com/aminzammou/cisq1-lingo/blob/9874b08d394af5e8312271024c08ac756fddf141/src/main/java/nl/hu/cisq1/lingo/trainer/application/TrainerService.java#L10-L40

# Repositories en entities
Ik denk dat Feedback niet meer serializable hoeft te zijn?

https://github.com/aminzammou/cisq1-lingo/blob/9874b08d394af5e8312271024c08ac756fddf141/src/main/java/nl/hu/cisq1/lingo/trainer/domain/Feedback.java#L19

**Comment by aminzammou** [comment]
dank u
